### ISSUE TITLE
[BUG]: `nanobind_add_module` does not work on OSX w/ Conda

### ISSUE THREAD

**Issue by gareth-cross** [wjakob/nanobind#123]
### Problem description

Testing configuration:
```
Mac OS X Ventura (13.0.1, ARM)
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:38:29) [Clang 13.0.1 ]
Conda 22.9.0
cmake version 3.24.2
```

I was hoping to gain context on the following code in `nanobind_add_module`:
```
if (APPLE)
   add_library(${name} MODULE ${ARG_UNPARSED_ARGUMENTS})
   target_include_directories(${name} PUBLIC ${Python_INCLUDE_DIRS})
   target_link_options(${name} PRIVATE -undefined suppress -flat_namespace)
else()
    Python_add_library(${name} MODULE ${ARG_UNPARSED_ARGUMENTS})
endif()
```
I admit I am not an expert in the CMake+Python combination, but the `if ()` branch does not appear to be required.

The breakage occurs because `Python_INCLUDE_DIRS` does not actually get defined by `find_package(Python ...)`.

What I tried (after removing the `APPLE` specific cmake logic) was the following:
```
find_package(Python 3.8 COMPONENTS Interpreter Development.Module REQUIRED)
nanobind_add_module(test_wrapper ...)
```
This appears to work fine, provided that `Python_add_library` is used.

If it seems correct and suitable to you, I can submit a PR that makes this change. Let me know if I have misunderstood something. Cheers.

**Comment by wjakob** [comment]
Hi @gareth-cross,

I haven't worked with conda much, so it's certainly possible that there are problems. @MatthiasKohl might also have ideas regarding what's wrong.

That said, I disagree with some of the claims above. For example, `Python_INCLUDE_DIRS` should certainly be defined, see the [documentation of FindPython](https://cmake.org/cmake/help/latest/module/FindPython.html). 

The `Python_add_library` command is problematic on Apple because it doesn't handle some linker-specific peculiarities. It's actually problematic on Windows as well because it cannot make stable ABI packages. 

In another recent commit (30befbd8ffe3af02bce28dd15fa7a019bba9a8b9), I completely removed it and now use ``add_library` for all platforms.

**Comment by gareth-cross** [comment]
> That said, I disagree with some of the claims above. For example, `Python_INCLUDE_DIRS` should certainly be defined, see the [documentation of FindPython](https://cmake.org/cmake/help/latest/module/FindPython.html).

It would appear that all my `Python_*` cmake variables are prefaced with an underscore, so `Python_INCLUDE_DIRS --> _Python_INCLUDE_DIRS`.

I have not been able to ascertain why yet. It would appear that for some variables this is expected, since they are internal ([link 1](https://gitlab.kitware.com/cmake/cmake/-/issues/22618), [link 2](https://gitlab.kitware.com/cmake/cmake/-/issues/20113)). That said, it seems like `Python_INCLUDE_DIRS` _should_ exist, but is incorrectly being prefixed with an underscore.

The issue does not happen if I use homebrew `cmake-3.25/python-3.10`, so at first glance it appears like a conda problem. I will close this. I will close this.
