### ISSUE TITLE
[BUG]: Python 3.12b1 support

### ISSUE THREAD

**Issue by geertj** [wjakob/nanobind#220]
### Problem description

Python 3.12 refactored the layout of the long object. The following patch is needed to compile modules against 3.12 (3.12b1 is the latest version as of this report). Unfortunately I won't have time to provide a properly tested PR that does the right thing with both the old and the new layout, but I'm creating this issue so this can at least be tracked.

```
--- common.cpp.orig     2023-05-30 04:18:52.879564557 +0000
+++ common.cpp  2023-05-30 04:18:57.819527549 +0000
@@ -824,7 +824,7 @@
             Py_ssize_t size = Py_SIZE(o);

             if (size == 0 || size == 1) {
-                digit value_d = lo->ob_digit[0];
+                digit value_d = lo->long_value.ob_digit[0];
                 T value = (T) value_d;
                 *out = value;
                 return sizeof(T) >= sizeof(digit) || value_d == (digit) value;
@@ -835,7 +835,7 @@
                     return false;
             } else {
                 if (size == -1) {
-                    sdigit value_d = - (sdigit) lo->ob_digit[0];
+                    sdigit value_d = - (sdigit) lo->long_value.ob_digit[0];
                     T value = (T) value_d;
                     *out = value;
                     return sizeof(T) >= sizeof(sdigit) || value_d == (sdigit) value;
```

**Comment by wjakob** [comment]
It's already fixed on the master branch as of https://github.com/wjakob/nanobind/commit/7549d16191adf87816001dc7fa2bb5876d07a167. The details of the fix are a bit more complicated than the diff you posted since one isn't supposed to call `Py_SIZE(o)` anymore. Instead, Python 3.12b1 exposes the functions `PyUnstable_Long_IsCompact` and `PyUnstable_Long_CompactValue` that encapsulate this more complicated logic.

**Comment by geertj** [comment]
Oh, thank you! I should have looked at master before posting this, my bad.
