### ISSUE TITLE
type caster for `char16_t` and `char32_t`

### ISSUE THREAD

**Issue by jube** [wjakob/nanobind#258]
Currently, there is no type caster for `char16_t` and `char32_t`. They could be mapped to Python int as `ord` in Python returns an int. I did this in my own code (I only needed `char32_t`), and it works. I think removing ` && !is_std_char_v<T>>` in `nb_cast.h` could work too.

```cc
namespace nanobind::detail {

template <>
struct type_caster<char32_t> {
    using Value = char32_t;
    template <typename T> using Cast = Value;

    static constexpr auto Name = const_name("char32_t");
    static constexpr bool IsClass = false;

    Value value = '\0';

    bool from_python(handle src, uint8_t flags, cleanup_list *cleanup) noexcept {
      if (!isinstance<int_>(src)) {
        return false;
      }

      value = static_cast<std::uint_least32_t>(int_(src));
      return true;
    }

    static handle from_cpp(char32_t value, rv_policy policy, cleanup_list *cleanup) {
      return int_(value);
    }

    explicit operator Value() {
        return value;
    }
};

}
```

**Comment by wjakob** [comment]
> Currently, there is no type caster for char16_t and char32_t.

This is intentional, I intentionally did not provide them as part of the default set of type casters since it's a bit of a fringe application, and people might want to implement them in various different ways.

If the default type caster clashes with yours, then that is something that could be fixed however. I am open to PRs in this direction.

**Comment by wjakob** [comment]
Closing this ticket since it's more of a feature request and not an issue of nanobind.
