### ISSUE TITLE
[BUG]: def(...) returns a class_ for enum_ types

### ISSUE THREAD

**Issue by matthewdcong** [wjakob/nanobind#303]
### Problem description

Based on https://docs.python.org/3/library/enum.html, it should be possible to define a custom implementation of `__repr__` for an Enum.

In order to implement this in nanobind for a `class_`, we can pass a suitable lambda function to `.def("__repr__")` which subsequently returns a `class_` enabling the chaining for definitions. However, in the case of an `enum_`, the inherited `.def(...)` call returns an `class_` instead of an `enum_` which causes subsequent chained calls to enumeration-specific functions such as `export_values()` to fail. The workaround is to perform a cast, or call all `enum_` functions before `class_` functions. See the example code where switching the order of the last two lines results in either a failed or successful compilation.

I believe the right way to address this would be to override `class_::def` with an `enum_::def` that returns an `enum_`, or provide polymorphic downcasting in some way or another.

### Reproducible example code

```text
enum class Foo : int { Bar = 0, Baz = 1};

#include <nanobind/nanobind.h>

namespace nb = nanobind;

NB_MODULE(test, m)
{
    nb::enum_<Foo>(m, "Foo")
        .value("Bar", Foo::Bar)
        .value("Baz", Foo::Baz)
        .def("__repr__", [](const Foo& foo) { return std::to_string(static_cast<int>(foo)); }) // switch this line with the following line and the code will compile and behave as expected
        .export_values();
}
```

**Comment by wjakob** [comment]
This sounds reasonable to me, though it's more of a feature request than a bug (this currently not officially documented functionality, and there is no reason why `nb::enum_` should exactly mirror the Python Enum class).

That said, it seems like a small change -- if you are willing to create a PR, then it is likely to be merged.

I will close this issue since those are reserved to actual bugs in the implementation of nanobind.
