### ISSUE TITLE
[OTHER]: (Feature request) nano-bind bazel support

### ISSUE THREAD

**Issue by MAminSFV** [wjakob/nanobind#609]
pybind11 has[ an official bazel wrapper ](https://github.com/pybind/pybind11_bazel)for the repo.

Currently, there is a community solution that is inspired by the same approach, [here](https://github.com/nicholasjng/nanobind-Bazel).

Is it possible to link the implementation or have the two projects under the same GitHub organization for more visilibity?

I believe that will help the community to come together and contribute in the same way.

I am curious about your thoughts on this.

**Comment by nicholasjng** [comment]
The implementation is linked in the documentation here: https://nanobind.readthedocs.io/en/latest/api_cmake.html (First bullet in the list)

Granted, it's not very visible because it is given as a small reference in the CMake document, which is decidedly _not_ where you'd look for Bazel support. I could offer contributing (and maintaining) a dedicated document on Bazel in the nanobind documentation if @wjakob is interested.

**Comment by wjakob** [comment]
Certainly, I'd be more than happy to host a bazel tutorial here as well. However, I do not plan to create a GitHub org or similar for the nanobind repo, if this is what @MAminSFV .

By the way, this is not an issue. Please do not open issue tickets for things that aren't an issue. What you meant to create is a discussion post.

**Comment by MAminSFV** [comment]
> I do not plan to create a GitHub org or similar for the nanobind repo, if this is what @MAminSFV was asking for.

@wjakob 
Thank you for the explanation.
Having a dedicated Bazel document will be beneficial and works as suggested by @nicholasjng and it is much appreciated.

I can also help by preparing a PR in the same fashion as it is done in the pybind docs and ask for your review.

> By the way, this is not an issue. Please do not open issue tickets for things that aren't an issue. What you meant to create is a discussion post.

Thank you for pointing this out, I was not aware of this tab.
I will use that section from now on.
