### ISSUE TITLE
[BUG]: std::iterator_traits<nanobind::detail::fast_iterator> is missing iterator_category

### ISSUE THREAD

**Issue by sogartar** [wjakob/nanobind#669]
### Problem description

It seems that `std::iterator_traits` is not properly implemented for `nanobind::detail::fast_iterator`. It is missing `iterator_category`.
I ran into this problem when compiling for Microsoft Visual Studio 2022.
The code in question looks something like
```
  std::optional<py::list> devices;
  std::transform(devices->begin(), devices->end(),
                 std::back_inserter(devices_vector), [](nanobind::handle h) {
                   ...
                 });
```
This will fail to compile with
```
error C2794: 'iterator_category': is not a member of any direct or indirect base class of 'std::iterator_traits<_Iter>'
        with
        [
            _Iter=nanobind::detail::fast_iterator
        ]
```

This happens on nanobind 2.0.

**Comment by wjakob** [comment]
Nanobind generally follows a no-STL design to the extent that this is possible. The internal iterators provide just enough support to be used in c++11-style ranged for loops and most definitely aren't STL valid iterators (which AFAIK involves a lot more boilerplate code than the missing type declaration you listed). Since adding this boilerplate code would not just apply to `fast_iterator` but also all of the other ones, I fear that this would lead to an undesirable header file bloat.
